// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from '@prismicio/types';
import type * as prismic from '@prismicio/client';

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for  Home page documents */
interface HomePageDocumentData {
  /**
   * Slice Zone field in * Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for * Home page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | NavbarSlice
  | ClientHighlightSlice;
/**
 *  Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<HomePageDocumentData>,
    'home_page',
    Lang
  >;
/** Content for Navbar documents */
interface NavbarDocumentData {
  /**
   * Navigation Items field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  navigation_items: prismicT.GroupField<
    Simplify<NavbarDocumentDataNavigationItemsItem>
  >;
  /**
   * logoUrl field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logourl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logourl: prismicT.ImageField<never>;
}
/**
 * Item in Navbar → Navigation Items
 *
 */
export interface NavbarDocumentDataNavigationItemsItem {
  /**
   * label field in *Navbar → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation_items[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField;
  /**
   * href field in *Navbar → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navigation_items[].href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  href: prismicT.LinkField;
}
/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, 'navbar', Lang>;
export type AllDocumentTypes = HomePageDocument | NavbarDocument;
/**
 * Item in ClientHighlight → Items
 *
 */
export interface ClientHighlightSliceDefaultItem {
  /**
   * name field in *ClientHighlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_highlight.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * logoUrl field in *ClientHighlight → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: client_highlight.items[].logourl
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  logourl: prismicT.LinkToMediaField;
  /**
   * href field in *ClientHighlight → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: client_highlight.items[].href
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  href: prismicT.LinkField;
}
/**
 * Default variation for ClientHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientHighlightSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ClientHighlightSliceDefaultItem>
>;
/**
 * Slice variation for *ClientHighlight*
 *
 */
type ClientHighlightSliceVariation = ClientHighlightSliceDefault;
/**
 * ClientHighlight Shared Slice
 *
 * - **API ID**: `client_highlight`
 * - **Description**: `ClientHighlight`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ClientHighlightSlice = prismicT.SharedSlice<
  'client_highlight',
  ClientHighlightSliceVariation
>;
/**
 * Primary content in HeroSection → Primary
 *
 */
interface HeroSectionSliceDefaultPrimary {
  /**
   * Small Text field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.small_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  small_text: prismicT.KeyTextField;
  /**
   * Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Sub Title field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  sub_title: prismicT.KeyTextField;
  /**
   * Button Text field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismicT.KeyTextField;
  /**
   * Product Image field in *HeroSection → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.product_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  product_image: prismicT.LinkToMediaField;
  /**
   * Background Image field in *HeroSection → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.background_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  background_image: prismicT.LinkToMediaField;
}
/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *HeroSection*
 *
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;
/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSlice = prismicT.SharedSlice<
  'hero_section',
  HeroSectionSliceVariation
>;
/**
 * Primary content in Navbar → Primary
 *
 */
interface NavbarSliceDefaultPrimary {
  /**
   * Logo field in *Navbar → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.primary.logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
}
/**
 * Item in Navbar → Items
 *
 */
export interface NavbarSliceDefaultItem {
  /**
   * Navigation label field in *Navbar → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.items[].navigation_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  navigation_label: prismicT.KeyTextField;
  /**
   * Navigation link field in *Navbar → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.items[].navigation_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  navigation_link: prismicT.LinkField;
}
/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<NavbarSliceDefaultPrimary>,
  Simplify<NavbarSliceDefaultItem>
>;
/**
 * Slice variation for *Navbar*
 *
 */
type NavbarSliceVariation = NavbarSliceDefault;
/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSlice = prismicT.SharedSlice<'navbar', NavbarSliceVariation>;
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      HomePageDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavigationItemsItem,
      NavbarDocument,
      AllDocumentTypes,
      ClientHighlightSliceDefaultItem,
      ClientHighlightSliceDefault,
      ClientHighlightSliceVariation,
      ClientHighlightSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceDefault,
      HeroSectionSliceVariation,
      HeroSectionSlice,
      NavbarSliceDefaultPrimary,
      NavbarSliceDefaultItem,
      NavbarSliceDefault,
      NavbarSliceVariation,
      NavbarSlice,
    };
  }
}
