// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  about_section: dynamic(() => import('./AboutSection')),
  client_highlight: dynamic(() => import('./ClientHighlight')),
  feature_section: dynamic(() => import('./FeatureSection')),
  hero_section: dynamic(() => import('./HeroSection')),
  menu_item: dynamic(() => import('./MenuItem')),
  navbar: dynamic(() => import('./Navbar')),
  service_section: dynamic(() => import('./ServiceSection')),
};
